fixed wording and made some changes to the formatting
Achsion/directorySpam pull request #2
Opened 2020-10-17 11:03 UTC by Alex1607

2021-11-16 20:38 UTC, Alex1607 commented
>:(

2022-04-26 20:31 UTC, Achsion commented
@Alex1607 please resolve the merge conflicts first

2023-01-03 21:20 UTC, Achsion requested changes
merge conflicts needs to be resolved ^^

2023-01-10 20:50 UTC, Achsion approved these changes

2023-01-10 20:51 UTC, merged